Strings = {
    -- blips
    ["purchasable_house"] = "Koopbaar huis",
    ["owned_house"] = "Eigen huis",
    ["access_house"] = "Huis waar je een sleutel van hebt",
    ["purchased_house"] = "Iemands huis",

    ["purchasable_apartment"] = "Koopbaar appartement",
    ["owned_apartment"] = "Eigen appartement",
    ["access_apartment"] = "Appartement waar je een sleutel van hebt",
    ["purchased_apartment"] = "Iemands appartement",

    ["ikea"] = "IKEA",
    ["robbery"] = "Robbery",

    -- text for buttons
    ["buy_house"] = "Druk ~INPUT_CONTEXT~ om te kopen ~b~%s~s~ (#%s) voor ~g~$%s~s~.",
    ["contact_rea"] = "Druk ~INPUT_CONTEXT~ om een ​​voorbeeld te bekijken %s [#%s]",
    ["contact_rea_nopreview"] = "Neem contact op met een makelaar om deze woning te kopen.",
    ["enter"] = "Druk ~INPUT_CONTEXT~ het gebouw binnen te gaan.",
    ["door"] = "Druk ~INPUT_CONTEXT~ om het deurmenu te openen (%s)",
    ["enter_ikea"] = "Druk ~INPUT_CONTEXT~ om de IKEA te betreden.\nDruk ~INPUT_DETONATE~ om uw meubels te verkopen.",
    ["furnishing"] = "Item: %s\nSnelheid: %s ~INPUT_COVER~ ~INPUT_TALK~\nGebruik ~INPUT_WEAPON_WHEEL_PREV~ ~INPUT_WEAPON_WHEEL_NEXT~ om het meubel omhoog/omlaag te bewegen\nGebruik ~INPUT_ATTACK~ ~INPUT_AIM~ om het object te draaien\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ ~INPUT_CELLPHONE_UP~ ~INPUT_CELLPHONE_DOWN~ om het object te verplaatsen\nDruk ~INPUT_DETONATE~ om het object naar jou te teleporteren\nDruk ~INPUT_FRONTEND_RDOWN~ om te bevestigen.\nDruk ~INPUT_FRONTEND_RRIGHT~ om te annuleren.",
    ["access_storage"] = "Druk ~INPUT_DETONATE~ om toegang te krijgen tot de opslag.",
    ["press_manage"] = "\nDruk ~INPUT_DETONATE~ om dit huis te beheren",
    ["enter_garage"] = "Druk ~INPUT_CONTEXT~ om de garage binnen te gaan.",
    ["store_garage"] = "Druk ~INPUT_CONTEXT~ om het voertuig te stallen.",
    ["breach_door"] = "\nDruk ~INPUT_DETONATE~ de deur te breken.",
    ["lockpick_door"] = "\nDruk ~INPUT_DETONATE~ de deur op slot te doen.",
    ["pole_dance"] = "Druk ~INPUT_CONTEXT~ om te paaldansen",
    ["stop_dancing"] = "Druk ~INPUT_VEH_DUCK~ om te stoppen met dansen",
    ["lap_dance"] = "Druk ~INPUT_CONTEXT~ om te lapdance\nDruk ~INPUT_VEH_EXIT~ om te zitten",
    ["storage_wardrobe"] = "Opberger of kledingkast",
    ["storage_option"] = "Open opslag",
    ["wardrobe_option"] = "Open kledingkast",
    ["select_outfit"] = "Selecteer een outfit",
    ["lockpicking"] = "Wanneer de vergrendeling vertraagt, bent u dicht bij de juiste positie.\nLockpicks links: %s\n\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ om het slot te draaien\n~INPUT_FRONTEND_RDOWN~ ontgrendelen\n~INPUT_FRONTEND_RRIGHT~ Annuleren",

    -- ikea
    ["viewing_furniture"] = "Browsen ~r~%s~s~.\nGebruik ~INPUT_REPLAY_BACK~ ~INPUT_REPLAY_ADVANCE~ artikel te wijzigen.\nGebruik ~INPUT_REPLAY_FFWD~ ~INPUT_REPLAY_REWIND~ om van categorie te veranderen.\nGebruik ~INPUT_MOVE_LEFT_ONLY~ ~INPUT_MOVE_RIGHT_ONLY~ om het object te draaien.\nGebruik ~INPUT_MOVE_UP_ONLY~ ~INPUT_MOVE_DOWN_ONLY~ om in/uit te zoomen.%s\nDruk ~INPUT_FRONTEND_RDOWN~ om te kopen ~b~%s~s~ voor ~g~$%s~s~.\nDruk ~INPUT_FRONTEND_RRIGHT~ om de IKEA te verlaten.",
    ["confirm_purchase"] = "Koop ~b~%s~s~ voor ~g~$%s~s~?\n\n~INPUT_FRONTEND_RDOWN~ kopen\n~INPUT_FRONTEND_RRIGHT~ Annuleren",
    ["purchased"] = "Gekocht %s voor ~g~$%s~s~.",
    ["storage"] = "\nIn dit artikel kun je spullen opbergen.",

    -- locked state
    ["locked"] = "Vergrendeld",
    ["unlocked"] = "Ontgrendeld",
    
    -- text for menus 
    ["house_key"] = "Huisesleutel",
    ["door_menu"] = "Deur menu",
    ["toggle_lock"] = "Vergrendel / Ontgrendel",
    ["exit"] = "Verlaat",
    ["furnish"] = "Inrichting",
    ["put_furniture"] = "Meubels plaatsen",
    ["manage_furniture"] = "Meubels beheren",
    ["amount_furniture"] = "x%s %s",
    ["confirm_house_purchase"] = "Aankoop %s voor <span style='color:lime'>$%s</span>",
    ["are_you_sure"] = "Kopen %s?",
    ["what_interior"] = "Welk interieur wil je?",
    ["interior_number"] = "Interieur #%s",
    ["remove_furniture"] = "Verwijderen %s?",
    ["inventory"] = "Opslag",
    ["inventory_weapons"] = "Wapen opslag",
    ["inventory_items"] = "Item opslag",
    ["black_money"] = "Zwart geld: <span style='color:red'>$%s</span>",
    ["cash"] = "Geld: <span style='color:lime'>$%s</span>",
    ["put"] = "Item storten",
    ["get"] = "Item opnemen",
    ["deposit"] = "Storting",
    ["withdraw"] = "Opnemen",
    ["weapons"] = "Wapens",
    ["items"] = "Items",
    ["amount_of"] = "Hoeveelheid van %s?",
    ["make_key_copy"] = "Maak een kopie van uw sleutel",
    ["resell_house"] = "Verkoop het huis terug voor <span style='color:lime'>$%s</span>",
    ["kick_someone_out"] = "Schop iemand eruit",
    ["kick_out?"] = "Uitschoppen %s?",
    ["kick_out"] = "Uitschoppen %s",
    ["preview"] = "Voorbeeld mogelijke interieurs",
    ["previewing"] = "~h~Interieurs bekijken\n\n~h~Voorvertoning interieur %s uit %s mogelijk.\nGebruik ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ om andere interieurs te bekijken\nDruk ~INPUT_FRONTEND_RRIGHT~ om de voorvertoning te stoppen.",
    ["previewing_nohelp"] = "~h~Bekijk huis~h~\nNeem contact op met een makelaar om dit huis te kopen.\nDruk ~INPUT_FRONTEND_RRIGHT~ om de voorvertoning te stoppen.",
    ["transfer_house"] = "Eigendom overdragen",
    ["transfer_property"] = "Eigendom overdragen aan %s?",
    ["none_nearby"] = "Er is niemand in de buurt",
    ["yes"] = "Ja",
    ["no"] = "Nee",
    ["no_outfits"] = "Je hebt geen outfits opgeslagen.",
    ["confirm_delete"] = "Outfit verwijderen \"%s\"?",
    ["equip_outfit"] = "Uitrusting uitrusten",
    ["delete_outfit"] = "Outfit verwijderen",

    -- text for notifications
    ["no_spawn"] = "Kon geen locatie vinden voor het huis/appartement.\n\nVraag uw servereigenaar om meer locaties toe te voegen.",
    ["error_locked"] = "Kon het huis/appartement niet betreden - de deur is op slot.",
    ["not_near_door"] = "U bent niet in de buurt van de deur en kunt deze dus niet op slot/ontgrendelen.",
    ["must_be_number"] = "U moet een nummer invoeren.",
    ["dont_have"] = "Je hebt niet zoveel.",
    ["not_enough"] = "Er is niet genoeg in de opslag.",
    ["cant_carry"] = "Je kunt niet zoveel dragen.", 
    ["has_items"] = "Dit object bevat items en u kunt het daarom niet verwijderen. Zorg ervoor dat u de opslagruimte leegmaakt!",
    ["someone_in_house_cant_sell"] = "Er is iemand in het huis - je kunt het nu niet verkopen!",
    ["cant_own_more"] = "U kunt niet meer eigendommen bezitten.",
    ["no_lockpicks"] = "Je hebt geen lockpicks.",
    ["robbery_progress"] = "LET OP!! Iemand berooft een huis! Controleer uw GPS!",
    ["you_got_kicked"] = "Je bent uit huis gezet.",
    ["house_spawned_transfer"] = "Er is iemand binnen, u kunt de woning niet overdragen.",
    ["nolonger_nearby"] = "De speler is niet meer in de buurt.",
    ["nearby_storage"] = "Er is iemand in de buurt en je kunt dus niet bij de opslag.",
    ["locked_door"] = "Je hebt de deur op slot gedaan",
    ["unlocked_door"] = "Je hebt de deur ontgrendeld",

    -- text for loading
    ["purchasing"] = "Inkoop",
    ["removing_furniture"] = "Meubels verwijderen",
    ["loading_object"] = "Object laden",
    ["loading_storage"] = "Opslag laden",

    -- other
    ["rotation"] = "Rotatie: %s",
    ["not_enough_cops"] = "Er is niet genoeg politie online!",
}